[application]

# App (Project) Name
name = "dxp-todo-frontend"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[fullstack]

[web.app]

# HTML title tag content
title = "index"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets", "server/src"]

# include `assets` in web platform
[web.resource]

# BUILD: The `web.resource` config has been deprecated in favor of head components and will be removed in a future release.
# To migrate to head components, remove `web.resource.style` and include the following rsx in your root component:         
# ```rust                                                                                                                  
# rsx! {                                                                                                                   
#     document::Link { rel: "stylesheet", href: asset!(css("public/tailwind.css")) }                                       
# }                                                                                                                        
# ```       

# CSS style file
# {% if styling == "Tailwind" %}
# style = ["/tailwind.css"]
# {% else %}
# style = ["public/tailwind.css"]
# {% endif %}

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []