name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    #https://doc.rust-lang.org/cargo/guide/continuous-integration.html
    strategy:
      matrix:
        toolchain:
          # - stable
          # - beta
          - nightly

    steps:
    - uses: actions/checkout@v4 #https://github.com/actions/checkout
      with:
        submodules: true
        clean: false

    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Build css-builder
      run: cargo build --manifest-path server/tools/css-builder/Cargo.toml --release --verbose

    - name: Build
      run: cargo build --features "github" --release --verbose

    - name: Run tests
      run: cargo test --verbose
